version: "3.9"
services:
  kolikargo-frontend:
    container_name: kolikargo-frontend
    image: kolikargo-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
